Name:           ros-indigo-linux-peripheral-interfaces
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS linux_peripheral_interfaces package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/linux_peripheral_interfaces
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-laptop-battery-monitor
BuildRequires:  ros-indigo-catkin

%description
Simple scripts which help utilise, monitor, interact with computer hardware
abstracted by a linux OS.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Nov 18 2014 Jihoon Lee <jihoonlee.in@gmail.com> - 0.1.1-0
- Autogenerated by Bloom

* Thu Aug 14 2014 Jihoon Lee <jihoonlee.in@gmail.com> - 0.1.0-0
- Autogenerated by Bloom

